<a href="https://colab.research.google.com/github/MohitNaren/ML/blob/main/MLlab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n = np.arange(15).reshape(5,3)
n1 = np.arange(6).reshape(3,2)
print(np.dot(n,n1))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [ ]:
n = np.arange(11)
n2 =(n[n%2 != 0])
print(n2)

[1 3 5 7 9]


In [ ]:
n = np.array([1,2,-1,2,-2,3,4,5])
n= [n>0]
print(n)

[array([ True,  True, False,  True, False,  True,  True,  True])]


In [ ]:
n = np.arange(1,11)
n[n % 2 == 0] *= -1
print(n)

[  1  -2   3  -4   5  -6   7  -8   9 -10]


In [ ]:
n = np.array([1,2,0,0,0,4,0,0])
print(np.nonzero(n))

(array([0, 1, 5]),)


In [ ]:
n= np.arange(1,11)
print(np.flip(n))

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
n1= np.arange(1,12)
n2= np.arange(11,21)
print(np.intersect1d(n1,n2))

[11]


In [ ]:
n = np.random.randint(0,4,10)
print(n.reshape(2,-1))

[[1 1 0 1 3]
 [0 1 2 3 2]]


In [ ]:
n= np.array([1,1,1,1,2,2,2,3,3,3,4,5,5,6])
print(np.bincount(n))

[0 4 3 3 1 2 1]


In [ ]:
n = np.ones((5,5))
n[1:-1,1:-1] = 0
print(n)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
n = np.random.random((2,2))
print(np.mean(n, axis=0))

[0.80575314 0.73499594]


In [ ]:
n = np.arange(10)
n1 = np.arange(10)
print(np.concatenate((n, n1)))

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [ ]:
n = np.array([[1,3,5,7,3,4,6,9,24,56,24,3]]).reshape(4,3)
print(n)
print(np.sort(n, axis=1))

[[ 1  3  5]
 [ 7  3  4]
 [ 6  9 24]
 [56 24  3]]
[[ 1  3  5]
 [ 3  4  7]
 [ 6  9 24]
 [ 3 24 56]]


In [ ]:
n = np.random.randint(10, 50, 20)
print(n)
print(np.percentile(n, 95))
print(np.percentile(n, 5))

[12 49 44 17 11 39 30 28 22 23 14 11 26 23 41 40 20 16 33 36]
44.25
11.0


In [ ]:
n = np.array([1,2,3,-1,-4,5,-3,5,6,7,-8])
n[n < 0] = 0
print(n)

[1 2 3 0 0 5 0 5 6 7 0]


In [ ]:
a1 = np.array([1,2,3,4])
a2 = np.array([2,3,4,5])
mse = np.mean((a1 - a2)**2)
print(mse)

1.0
